/******************************************************************************
 * Developed By: Snehal V Sutar. 
 * Net ID: svs130130
 * Class Name: RecordAttGUI
 * Function: GUI Layer for Recording Attendance.
 * Patterns: Indirection, Pure Fabrication,Low Coupling.
 ******************************************************************************/

package attendancetracker.recordattendance;

import attendancetracker.graphforselectedcourse.GraphForSelCourseGUI;
import attendancetracker.MainScreen;
import attendancetracker.chartforselectedcourse.ChartGUI;
import attendancetracker.courseregistration.CourseRegTechSerLayer;
import attendancetracker.course.CourseStruct;
import attendancetracker.course.CourseDomainLayer;
import attendancetracker.student.StudentTechSerLayer;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SnehalSutar
 */
public class RecordAttGUI extends javax.swing.JFrame {

    RecAttDomainLayer recAttProc;//  new CourseDomainLayer();
        
    /**
     * Creates new form RecordAttendance
     */
    public RecordAttGUI() {
        recAttProc = new RecAttDomainLayer();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studAttTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        courseIDCombo = new javax.swing.JComboBox();
        dateMonthCombo = new javax.swing.JComboBox();
        dateDayCombo = new javax.swing.JComboBox();
        dateYearCombo = new javax.swing.JComboBox();
        courseName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        homePage = new javax.swing.JButton();
        statusBar = new javax.swing.JLabel();
        getAttendance = new javax.swing.JButton();
        graphButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        chartButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        studAttTable.setBackground(new java.awt.Color(204, 255, 204));
        studAttTable.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        studAttTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student ID", "First Name", "Middle Name", "Last Name", "Present"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(studAttTable);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("CourseID");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Date");

        courseIDCombo.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        courseIDCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                courseIDComboItemStateChanged(evt);
            }
        });

        dateMonthCombo.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        dateMonthCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        dateMonthCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dateMonthComboItemStateChanged(evt);
            }
        });

        dateDayCombo.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        dateDayCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dateDayCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dateDayComboItemStateChanged(evt);
            }
        });

        dateYearCombo.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        dateYearCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        dateYearCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dateYearComboItemStateChanged(evt);
            }
        });

        courseName.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        courseName.setText("jLabel3");

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel3.setText("Month");

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel4.setText("Day");

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel5.setText("Year");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(courseIDCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateMonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(dateDayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(courseName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(dateYearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(courseIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateMonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateDayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateYearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        saveButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        homePage.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        homePage.setText("HomePage");
        homePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePageMouseClicked(evt);
            }
        });
        homePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePageActionPerformed(evt);
            }
        });

        statusBar.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        statusBar.setText("Status Bar");

        getAttendance.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        getAttendance.setText("Get Attendance Sheet");
        getAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAttendanceActionPerformed(evt);
            }
        });

        graphButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        graphButton.setText("Get Graph for Selected Course");
        graphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel6.setText("Record Attendance");

        chartButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        chartButton.setText("Chart for Selected Course");
        chartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(251, 251, 251)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(homePage))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(saveButton)
                                    .addGap(279, 279, 279)
                                    .addComponent(chartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(graphButton))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(131, 131, 131)
                                        .addComponent(getAttendance)))))))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(homePage))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getAttendance))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(graphButton)
                    .addComponent(chartButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBar))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homePageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePageMouseClicked
        this.setVisible(false);
        dispose();
        MainScreen mainScr = new MainScreen();
        mainScr.setVisible(true);        
    }//GEN-LAST:event_homePageMouseClicked

    public void close()
    {
    WindowEvent winclosingevent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclosingevent);
    }
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        CourseDomainLayer courseProc = new CourseDomainLayer();
        CourseStruct courseArray[] = courseProc.getCourseList();
        CourseStruct course;
        for(int i= 0; i<CourseDomainLayer.numOfCourses;i++){
            //course = new CourseStruct();
            course = courseArray[i];
            courseIDCombo.addItem(course.courseID);
        }
        
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        String dateStr;
        dateStr = dateFormat.format(date);
        
        dateYearCombo.setSelectedItem(dateStr.substring(0, 4));
        dateMonthCombo.setSelectedItem(dateStr.substring(5, 7));
        dateDayCombo.setSelectedItem(dateStr.substring(8,10));
        
        //studAttTable.setVisible(false);
        
    }//GEN-LAST:event_formWindowActivated

    
    
    /***************************************************************************
     * Reload the Student table from Database and display in the display table.
     **************************************************************************/
    public void refreshStudentTable(){

        Object[][] data = recAttProc.updateTable();
        StudentTechSerLayer studDb = new StudentTechSerLayer();
        
        //tudAttTable.set
        
        for(int row = 0; row<RecAttDomainLayer.numOfStudents; row++){
            for(int col = 0 ; col<=4; col++){
                studAttTable.setValueAt(data[row][col], row, col);
            }
        }
    }
    
    
    private void homePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePageActionPerformed
        this.setVisible(false);
        dispose();
        //close();
        MainScreen mainScr = new MainScreen();
        mainScr.setVisible(true);
    }//GEN-LAST:event_homePageActionPerformed

    private void courseIDComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_courseIDComboItemStateChanged
        CourseDomainLayer courseProc = new CourseDomainLayer();
        CourseStruct courseArray[] = courseProc.getCourseList();
        CourseStruct course;
        for(int i= 0; i<courseProc.numOfCourses;i++){
            course = new CourseStruct();
            course = courseArray[i];
            if(evt.getItem().equals(course.courseID) ){
                courseName.setText(course.courseName);
            }
        }
        studAttTable.setVisible(false);
        
       
        
    }//GEN-LAST:event_courseIDComboItemStateChanged

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        RecAttStruct recAtt = new RecAttStruct();
        recAtt.courseID = (String)courseIDCombo.getSelectedItem();
        recAtt.day      = (String)dateDayCombo.getSelectedItem();
        recAtt.month    = (String)dateMonthCombo.getSelectedItem();
        recAtt.year     = (String)dateYearCombo.getSelectedItem();
        
        RecAttDomainLayer recAttProc = new RecAttDomainLayer();
        String str = recAttProc.saveAttendance(recAtt, studAttTable);
        
        statusBar.setText(str);

    }//GEN-LAST:event_saveButtonActionPerformed

    private void getAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAttendanceActionPerformed
        studAttTable.setVisible(true);
        
        
         // Clear the Table which is used to display the students which are 
        // registered for the selected course.
         for(int row = 0; row<60; row++){
            for(int col = 0 ; col<=4; col++){
                studAttTable.setValueAt(null, row, col);
            }
        }
         //Check if file exists for current CourseStruct and current given date.
          RecAttStruct recAtt = new RecAttStruct();
          recAtt.courseID = (String)courseIDCombo.getSelectedItem();
          recAtt.day      = (String)dateDayCombo.getSelectedItem();
          recAtt.month    = (String)dateMonthCombo.getSelectedItem();
          recAtt.year     = (String)dateYearCombo.getSelectedItem();
         Object[][] data;
         // Fill the table with the students who are registered for the selected 
         // course.
          //Object[][] data = recAttProc.getStudentsEnrolledForCourse(courseIDCombo.getSelectedItem().toString());
        data = recAttProc.checkIfAttendanceMarked(recAtt);
        
          for(int row = 0; row<CourseRegTechSerLayer.courseNumForCourse; row++){
            for(int col = 0 ; col<=4; col++){
                studAttTable.setValueAt(data[row][col], row, col);
            }
        }
          if(RecAttDomainLayer.fileFound==1)
              statusBar.setText("Attendace already recorded for this course"
                      + " and the date. Please make required changes in the"
                      + "attendance and SAVE.");
          else
              statusBar.setText("Please uncheck the boxes for Absent students"
                                + " and SAVE.");
    }//GEN-LAST:event_getAttendanceActionPerformed

    private void graphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphButtonActionPerformed
        String fileName = (String)courseIDCombo.getSelectedItem() +".txt";
        RecAttTechSerLayer recordAttTLyr = new RecAttTechSerLayer();
        if(recordAttTLyr.checkIfFileExists(fileName)==1){
        this.dispose();
        GraphForSelCourseGUI graph = new GraphForSelCourseGUI((String)courseIDCombo.getSelectedItem());
        graph.setVisible(true);
        }
        else
            statusBar.setText("Attendance not even marked once for course"
                    + (String)courseIDCombo.getSelectedItem() +
                    ". Please select another course.");
    }//GEN-LAST:event_graphButtonActionPerformed

    private void chartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartButtonActionPerformed
        String fileName = (String)courseIDCombo.getSelectedItem() +".txt";
        RecAttTechSerLayer recordAttTLyr = new RecAttTechSerLayer();
        if(recordAttTLyr.checkIfFileExists(fileName)==1){
        this.dispose();
        ChartGUI chart = new ChartGUI((String)courseIDCombo.getSelectedItem());
        chart.setVisible(true);
        }
        else
            statusBar.setText("Attendance not even marked once for course"
                    + (String)courseIDCombo.getSelectedItem() +
                    ". Please select another course.");
    }//GEN-LAST:event_chartButtonActionPerformed

    private void dateMonthComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dateMonthComboItemStateChanged
        studAttTable.setVisible(false);
    }//GEN-LAST:event_dateMonthComboItemStateChanged

    private void dateYearComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dateYearComboItemStateChanged
        studAttTable.setVisible(false);
    }//GEN-LAST:event_dateYearComboItemStateChanged

    private void dateDayComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dateDayComboItemStateChanged
        studAttTable.setVisible(false);
    }//GEN-LAST:event_dateDayComboItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordAttGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordAttGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordAttGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordAttGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecordAttGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chartButton;
    private javax.swing.JComboBox courseIDCombo;
    private javax.swing.JLabel courseName;
    private javax.swing.JComboBox dateDayCombo;
    private javax.swing.JComboBox dateMonthCombo;
    private javax.swing.JComboBox dateYearCombo;
    private javax.swing.JButton getAttendance;
    private javax.swing.JButton graphButton;
    private javax.swing.JButton homePage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel statusBar;
    private javax.swing.JTable studAttTable;
    // End of variables declaration//GEN-END:variables
}
